name: Handle New Release

on:
  release:
    types: [published] # Triggers when a release is officially published

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script
        run: echo "New release detected: ${{ github.event.release.tag_name }}"